name: Wiki CI Workflow

on:
  push:
    branches:
      - main  

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      
      - name: Build and Push Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

  deploy-server:
    runs-on: ubuntu-latest
    needs: [build_and_push]
    steps:
      # add necessary steps to SSH into the server and pull the Docker image
      - name: SSH into server and pull Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd portfolio
            docker-compose down
            docker-compose pull 
            docker-compose up -d
